name: Deploy API

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.m2/repository
            scripts/node_modules
          key: ${{ runner.os }}-maven-node-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-node-

      - name: Deploy to Heroku
        if: github.event_name == 'push'
        run: mvn heroku:deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
